#!/usr/bin/env ruby
# Usage: redcarpet [<file>...]
# Convert one or more Markdown files to HTML and write to standard output. With
# no <file> or when <file> is '-', read Markdown source text from standard input.
if ARGV.include?('--help')
  File.read(__FILE__).split("\n").grep(/^# /).each do |line|
    puts line[2..-1]
  end
  exit 0
end

require 'redcarpet'
STDOUT.write(Redcarpet::Markdown.new(Redcarpet::Render::HTML,
  {
    :fenced_code_blocks => true,
    :strikethrough => true,
    :lax_html_blocks => true,
    :tables => true,
    :no_intra_emphasis => true
  }).render(ARGF.read))
